name: rag-faiss
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - faiss-gpu=1.9.0
  - pip
  - pip:
      - -r requirements.txt
